 window.LINGUA_DATA = window.LINGUA_DATA || {};
  window.LINGUA_DATA.A2 = [
    // ─── PAST SIMPLE ───
    { id: 'a2_1', type: 'choice', q: 'I ___ to London last year.', opts: ['go','went','gone','going'], correct: 1, topic: 'Past Simple' },
    { id: 'a2_2', type: 'choice', q: 'She ___ a movie yesterday.', opts: ['watch','watched','watching','watches'], correct: 1, topic: 'Past Simple' },
    { id: 'a2_3', type: 'choice', q: 'They ___ at home last night.', opts: ['was','were','are','is'], correct: 1, topic: 'Past Simple' },
    { id: 'a2_4', type: 'choice', q: 'He ___ a new car last week.', opts: ['buy','bought','buys','buying'], correct: 1, topic: 'Past Simple' },
    { id: 'a2_5', type: 'choice', q: 'We ___ to the beach on Sunday.', opts: ['go','went','goes','going'], correct: 1, topic: 'Past Simple' },
    { id: 'a2_6', type: 'choice', q: 'I ___ my keys this morning.', opts: ['lose','lost','loses','losing'], correct: 1, topic: 'Past Simple' },
    { id: 'a2_7', type: 'choice', q: 'She ___ breakfast at 8 a.m.', opts: ['have','had','has','having'], correct: 1, topic: 'Past Simple' },
    { id: 'a2_8', type: 'choice', q: 'He ___ me yesterday.', opts: ['call','called','calls','calling'], correct: 1, topic: 'Past Simple' },
    { id: 'a2_9', type: 'choice', q: 'They ___ in Paris for two years.', opts: ['live','lived','lives','living'], correct: 1, topic: 'Past Simple' },
    { id: 'a2_10', type: 'choice', q: 'I ___ her at the party.', opts: ['see','saw','seen','seeing'], correct: 1, topic: 'Past Simple' },

    // ─── IRREGULAR VERBS ───
    { id: 'a2_11', type: 'choice', q: 'Past form of "eat":', opts: ['eated','ate','eaten','eating'], correct: 1, topic: 'Неправильные' },
    { id: 'a2_12', type: 'choice', q: 'Past form of "drink":', opts: ['drinked','drank','drunk','drinking'], correct: 1, topic: 'Неправильные' },
    { id: 'a2_13', type: 'choice', q: 'Past form of "write":', opts: ['writed','wrote','written','writing'], correct: 1, topic: 'Неправильные' },
    { id: 'a2_14', type: 'choice', q: 'Past form of "speak":', opts: ['speaked','spoke','spoken','speaking'], correct: 1, topic: 'Неправильные' },
    { id: 'a2_15', type: 'choice', q: 'Past form of "take":', opts: ['taked','took','taken','taking'], correct: 1, topic: 'Неправильные' },
    { id: 'a2_16', type: 'choice', q: 'Past form of "give":', opts: ['gived','gave','given','giving'], correct: 1, topic: 'Неправильные' },
    { id: 'a2_17', type: 'choice', q: 'Past form of "make":', opts: ['maked','made','making','makes'], correct: 1, topic: 'Неправильные' },
    { id: 'a2_18', type: 'choice', q: 'Past form of "find":', opts: ['finded','found','finding','finds'], correct: 1, topic: 'Неправильные' },
    { id: 'a2_19', type: 'choice', q: 'Past form of "think":', opts: ['thinked','thought','thinking','thinks'], correct: 1, topic: 'Неправильные' },
    { id: 'a2_20', type: 'choice', q: 'Past form of "come":', opts: ['comed','came','coming','comes'], correct: 1, topic: 'Неправильные' },

    // ─── FUTURE ───
    { id: 'a2_21', type: 'choice', q: 'I ___ call you tomorrow.', opts: ['will','am','do','did'], correct: 0, topic: 'Будущее' },
    { id: 'a2_22', type: 'choice', q: 'She ___ going to travel next week.', opts: ['is','are','am','be'], correct: 0, topic: 'Будущее' },
    { id: 'a2_23', type: 'choice', q: 'We ___ visit grandma on Sunday.', opts: ['will','do','did','are'], correct: 0, topic: 'Будущее' },
    { id: 'a2_24', type: 'choice', q: 'They ___ going to buy a house.', opts: ['is','are','am','be'], correct: 1, topic: 'Будущее' },
    { id: 'a2_25', type: 'choice', q: 'I think it ___ rain tomorrow.', opts: ['will','is','does','did'], correct: 0, topic: 'Будущее' },

    // ─── PRESENT CONTINUOUS ───
    { id: 'a2_26', type: 'choice', q: 'He ___ TV right now.', opts: ['watch','watches','is watching','watched'], correct: 2, topic: 'Present Continuous' },
    { id: 'a2_27', type: 'choice', q: 'I ___ reading a book.', opts: ['am','is','are','be'], correct: 0, topic: 'Present Continuous' },
    { id: 'a2_28', type: 'choice', q: 'They ___ playing football.', opts: ['am','is','are','be'], correct: 2, topic: 'Present Continuous' },
    { id: 'a2_29', type: 'choice', q: 'She ___ dinner at the moment.', opts: ['cook','cooks','is cooking','cooked'], correct: 2, topic: 'Present Continuous' },
    { id: 'a2_30', type: 'choice', q: 'We ___ waiting for you.', opts: ['am','is','are','be'], correct: 2, topic: 'Present Continuous' },
    { id: 'a2_31', type: 'choice', q: 'What ___ you doing?', opts: ['am','is','are','be'], correct: 2, topic: 'Present Continuous' },
    { id: 'a2_32', type: 'choice', q: 'Look! It ___ raining.', opts: ['am','is','are','be'], correct: 1, topic: 'Present Continuous' },
    { id: 'a2_33', type: 'choice', q: 'She ___ to music right now.', opts: ['listen','listens','is listening','listened'], correct: 2, topic: 'Present Continuous' },

    // ─── MODAL VERBS ───
    { id: 'a2_34', type: 'choice', q: 'I ___ swim very well.', opts: ['can','must','should','may'], correct: 0, topic: 'Модальные' },
    { id: 'a2_35', type: 'choice', q: 'You ___ stop at the red light.', opts: ['can','must','may','could'], correct: 1, topic: 'Модальные' },
    { id: 'a2_36', type: 'choice', q: 'You ___ see a doctor.', opts: ['should','can','may','must'], correct: 0, topic: 'Модальные' },
    { id: 'a2_37', type: 'choice', q: '___ I open the window?', opts: ['May','Must','Should','Can'], correct: 0, topic: 'Модальные' },
    { id: 'a2_38', type: 'choice', q: 'She ___ play the piano.', opts: ['can','must','should','may'], correct: 0, topic: 'Модальные' },
    { id: 'a2_39', type: 'choice', q: 'We ___ hurry, the train is leaving.', opts: ['can','must','may','could'], correct: 1, topic: 'Модальные' },
    { id: 'a2_40', type: 'choice', q: 'He ___ not come today.', opts: ['can','must','may','should'], correct: 2, topic: 'Модальные' },

    // ─── COMPARATIVES ───
    { id: 'a2_41', type: 'choice', q: 'This book is ___ than that one.', opts: ['good','better','best','more good'], correct: 1, topic: 'Степени' },
    { id: 'a2_42', type: 'choice', q: 'She is ___ girl in the class.', opts: ['smart','smarter','the smartest','most smart'], correct: 2, topic: 'Степени' },
    { id: 'a2_43', type: 'choice', q: 'My car is ___ than yours.', opts: ['fast','faster','fastest','more fast'], correct: 1, topic: 'Степени' },
    { id: 'a2_44', type: 'choice', q: 'This is ___ film I have ever seen.', opts: ['bad','worse','the worst','baddest'], correct: 2, topic: 'Степени' },
    { id: 'a2_45', type: 'choice', q: 'He is ___ than his brother.', opts: ['tall','taller','tallest','more tall'], correct: 1, topic: 'Степени' },
    { id: 'a2_46', type: 'choice', q: 'Today is ___ than yesterday.', opts: ['hot','hotter','hottest','more hot'], correct: 1, topic: 'Степени' },
    { id: 'a2_47', type: 'choice', q: 'This is ___ expensive restaurant in town.', opts: ['more','most','the most','the more'], correct: 2, topic: 'Степени' },

    // ─── SOME / ANY / MUCH / MANY ───
    { id: 'a2_48', type: 'choice', q: 'I have ___ apples.', opts: ['some','any','much','a'], correct: 0, topic: 'Some/Any' },
    { id: 'a2_49', type: 'choice', q: 'Do you have ___ money?', opts: ['some','any','much','a'], correct: 1, topic: 'Some/Any' },
    { id: 'a2_50', type: 'choice', q: 'There isn\'t ___ milk.', opts: ['some','any','many','a'], correct: 1, topic: 'Some/Any' },
    { id: 'a2_51', type: 'choice', q: 'How ___ people are there?', opts: ['much','many','some','any'], correct: 1, topic: 'Much/Many' },
    { id: 'a2_52', type: 'choice', q: 'How ___ water do you need?', opts: ['much','many','some','any'], correct: 0, topic: 'Much/Many' },
    { id: 'a2_53', type: 'choice', q: 'There are ___ books on the shelf.', opts: ['much','many','a lot','any'], correct: 1, topic: 'Much/Many' },
    { id: 'a2_54', type: 'choice', q: 'I don\'t have ___ time.', opts: ['many','much','some','a'], correct: 1, topic: 'Much/Many' },

    // ─── PREPOSITIONS (продолжение) ───
    { id: 'a2_55', type: 'choice', q: 'I am interested ___ music.', opts: ['in','on','at','for'], correct: 0, topic: 'Предлоги' },
    { id: 'a2_56', type: 'choice', q: 'She is good ___ math.', opts: ['in','at','on','for'], correct: 1, topic: 'Предлоги' },
    { id: 'a2_57', type: 'choice', q: 'I am afraid ___ dogs.', opts: ['of','from','in','on'], correct: 0, topic: 'Предлоги' },
    { id: 'a2_58', type: 'choice', q: 'Thank you ___ your help.', opts: ['for','to','at','in'], correct: 0, topic: 'Предлоги' },
    { id: 'a2_59', type: 'choice', q: 'I am waiting ___ the bus.', opts: ['for','to','at','in'], correct: 0, topic: 'Предлоги' },
    { id: 'a2_60', type: 'choice', q: 'She is married ___ John.', opts: ['with','to','for','at'], correct: 1, topic: 'Предлоги' },
    { id: 'a2_61', type: 'choice', q: 'I am tired ___ working.', opts: ['of','from','with','at'], correct: 0, topic: 'Предлоги' },
    { id: 'a2_62', type: 'choice', q: 'Look ___ this picture!', opts: ['at','on','in','for'], correct: 0, topic: 'Предлоги' },

    // ─── QUESTIONS ───
    { id: 'a2_63', type: 'choice', q: 'Where ___ you go yesterday?', opts: ['do','did','does','are'], correct: 1, topic: 'Вопросы' },
    { id: 'a2_64', type: 'choice', q: 'What ___ she doing now?', opts: ['is','are','do','does'], correct: 0, topic: 'Вопросы' },
    { id: 'a2_65', type: 'choice', q: 'How ___ you go to work?', opts: ['do','does','is','are'], correct: 0, topic: 'Вопросы' },
    { id: 'a2_66', type: 'choice', q: 'When ___ he arrive?', opts: ['do','did','does','is'], correct: 1, topic: 'Вопросы' },
    { id: 'a2_67', type: 'choice', q: 'Why ___ you crying?', opts: ['is','are','do','does'], correct: 1, topic: 'Вопросы' },
    { id: 'a2_68', type: 'choice', q: 'Who ___ you meet yesterday?', opts: ['do','did','does','was'], correct: 1, topic: 'Вопросы' },

    // ─── TRANSLATE ───
    { id: 'a2_69', type: 'translate', q: 'Переведи: «Я ходил в кино вчера»', answers: ['i went to the cinema yesterday','i went to the movies yesterday'], topic: 'Перевод' },
    { id: 'a2_70', type: 'translate', q: 'Переведи: «Она работает в банке»', answers: ['she works in a bank','she works at a bank'], topic: 'Перевод' },
    { id: 'a2_71', type: 'translate', q: 'Переведи: «Мы поедем в Париж завтра»', answers: ['we will go to paris tomorrow','we are going to paris tomorrow'], topic: 'Перевод' },
    { id: 'a2_72', type: 'translate', q: 'Переведи: «Я не могу прийти сегодня»', answers: ['i cannot come today','i cant come today'], topic: 'Перевод' },
    { id: 'a2_73', type: 'translate', q: 'Переведи: «Он читает книгу сейчас»', answers: ['he is reading a book now'], topic: 'Перевод' },
    { id: 'a2_74', type: 'translate', q: 'Переведи: «Тебе следует больше отдыхать»', answers: ['you should rest more','you should have more rest'], topic: 'Перевод' },
    { id: 'a2_75', type: 'translate', q: 'Переведи: «Этот дом больше того»', answers: ['this house is bigger than that one','this house is bigger than that'], topic: 'Перевод' },
    { id: 'a2_76', type: 'translate', q: 'Переведи: «У меня болит голова»', answers: ['i have a headache','my head hurts'], topic: 'Перевод' },
    { id: 'a2_77', type: 'translate', q: 'Переведи: «Сколько это стоит?»', answers: ['how much does it cost','how much is it'], topic: 'Перевод' },
    { id: 'a2_78', type: 'translate', q: 'Переведи: «Я забыл свои ключи»', answers: ['i forgot my keys'], topic: 'Перевод' },
    { id: 'a2_79', type: 'translate', q: 'Переведи: «Она хорошо готовит»', answers: ['she cooks well','she is a good cook'], topic: 'Перевод' },
    { id: 'a2_80', type: 'translate', q: 'Переведи: «Мы живём здесь 5 лет»', answers: ['we have lived here for 5 years','weve lived here for five years'], topic: 'Перевод' },
    { id: 'a2_81', type: 'translate', q: 'Переведи: «Я хочу поехать в отпуск»', answers: ['i want to go on holiday','i want to go on vacation'], topic: 'Перевод' },
    { id: 'a2_82', type: 'translate', q: 'Переведи: «Он не любит рыбу»', answers: ['he does not like fish','he doesnt like fish'], topic: 'Перевод' },
    { id: 'a2_83', type: 'translate', q: 'Переведи: «Погода сегодня хорошая»', answers: ['the weather is nice today','the weather is good today'], topic: 'Перевод' },
    { id: 'a2_84', type: 'translate', q: 'Переведи: «Мне нужна твоя помощь»', answers: ['i need your help'], topic: 'Перевод' },
    { id: 'a2_85', type: 'translate', q: 'Переведи: «Как долго ты здесь?»', answers: ['how long have you been here','how long are you here'], topic: 'Перевод' },
    { id: 'a2_86', type: 'translate', q: 'Переведи: «Я пойду спать через час»', answers: ['i will go to bed in an hour','i will go to sleep in an hour'], topic: 'Перевод' },
    { id: 'a2_87', type: 'translate', q: 'Переведи: «Это моя любимая песня»', answers: ['this is my favorite song','this is my favourite song'], topic: 'Перевод' },
    { id: 'a2_88', type: 'translate', q: 'Переведи: «Мне нравится учить английский»', answers: ['i like learning english','i like to learn english'], topic: 'Перевод' },

    // ─── LISTEN ───
    { id: 'a2_89', type: 'listen', q: 'Прослушай и напиши', audio: 'I went to the cinema yesterday.', answers: ['i went to the cinema yesterday','i went to the movies yesterday'], topic: 'Аудирование' },
    { id: 'a2_90', type: 'listen', q: 'Прослушай и напиши', audio: 'She is working in a hospital.', answers: ['she is working in a hospital','shes working in a hospital'], topic: 'Аудирование' },
    { id: 'a2_91', type: 'listen', q: 'Прослушай и напиши', audio: 'We will travel next summer.', answers: ['we will travel next summer','well travel next summer'], topic: 'Аудирование' },
    { id: 'a2_92', type: 'listen', q: 'Прослушай и напиши', audio: 'Can you help me, please?', answers: ['can you help me please','can you help me, please'], topic: 'Аудирование' },
    { id: 'a2_93', type: 'listen', q: 'Прослушай и напиши', audio: 'I have never been to Paris.', answers: ['i have never been to paris','ive never been to paris'], topic: 'Аудирование' },
    { id: 'a2_94', type: 'listen', q: 'Прослушай и напиши', audio: 'The weather is very nice today.', answers: ['the weather is very nice today'], topic: 'Аудирование' },
    { id: 'a2_95', type: 'listen', q: 'Прослушай и напиши', audio: 'How much does it cost?', answers: ['how much does it cost'], topic: 'Аудирование' },
    { id: 'a2_96', type: 'listen', q: 'Прослушай и напиши', audio: 'I would like to book a table.', answers: ['i would like to book a table','id like to book a table'], topic: 'Аудирование' },
    { id: 'a2_97', type: 'listen', q: 'Прослушай и напиши', audio: 'She speaks three languages.', answers: ['she speaks three languages'], topic: 'Аудирование' },
    { id: 'a2_98', type: 'listen', q: 'Прослушай и напиши', audio: 'We are going to the beach.', answers: ['we are going to the beach','were going to the beach'], topic: 'Аудирование' },
    { id: 'a2_99', type: 'listen', q: 'Прослушай и напиши', audio: 'He is taller than his brother.', answers: ['he is taller than his brother','hes taller than his brother'], topic: 'Аудирование' },
    { id: 'a2_100', type: 'listen', q: 'Прослушай и напиши', audio: 'I forgot my phone at home.', answers: ['i forgot my phone at home'], topic: 'Аудирование' },

    // ─── SPEAK ───
    { id: 'a2_101', type: 'speak', q: 'Произнеси вслух', target: 'I went to the cinema yesterday.', topic: 'Произношение' },
    { id: 'a2_102', type: 'speak', q: 'Произнеси вслух', target: 'She is working in a hospital.', topic: 'Произношение' },
    { id: 'a2_103', type: 'speak', q: 'Произнеси вслух', target: 'Can you help me, please?', topic: 'Произношение' },
    { id: 'a2_104', type: 'speak', q: 'Произнеси вслух', target: 'I have never been to Paris.', topic: 'Произношение' },
    { id: 'a2_105', type: 'speak', q: 'Произнеси вслух', target: 'The weather is very nice today.', topic: 'Произношение' },
    { id: 'a2_106', type: 'speak', q: 'Произнеси вслух', target: 'How much does it cost?', topic: 'Произношение' },
    { id: 'a2_107', type: 'speak', q: 'Произнеси вслух', target: 'I would like to book a table.', topic: 'Произношение' },
    { id: 'a2_108', type: 'speak', q: 'Произнеси вслух', target: 'What are you doing right now?', topic: 'Произношение' },
    { id: 'a2_109', type: 'speak', q: 'Произнеси вслух', target: 'We will travel next summer.', topic: 'Произношение' },
    { id: 'a2_110', type: 'speak', q: 'Произнеси вслух', target: 'I am learning English every day.', topic: 'Произношение' },

    // ─── WORD ORDER ───
    { id: 'a2_111', type: 'order', q: 'Собери предложение', words: ['I','went','to','London','last','year'], correct: 'I went to London last year', topic: 'Порядок слов' },
    { id: 'a2_112', type: 'order', q: 'Собери предложение', words: ['She','is','reading','a','book','now'], correct: 'She is reading a book now', topic: 'Порядок слов' },
    { id: 'a2_113', type: 'order', q: 'Собери предложение', words: ['We','will','go','to','Paris','tomorrow'], correct: 'We will go to Paris tomorrow', topic: 'Порядок слов' },
    { id: 'a2_114', type: 'order', q: 'Собери предложение', words: ['You','should','see','a','doctor'], correct: 'You should see a doctor', topic: 'Порядок слов' },
    { id: 'a2_115', type: 'order', q: 'Собери предложение', words: ['This','house','is','bigger','than','that'], correct: 'This house is bigger than that', topic: 'Порядок слов' },
    { id: 'a2_116', type: 'order', q: 'Собери предложение', words: ['I','can','speak','English','well'], correct: 'I can speak English well', topic: 'Порядок слов' },
    { id: 'a2_117', type: 'order', q: 'Собери предложение', words: ['They','were','at','home','yesterday'], correct: 'They were at home yesterday', topic: 'Порядок слов' },
    { id: 'a2_118', type: 'order', q: 'Собери предложение', words: ['She','has','two','children'], correct: 'She has two children', topic: 'Порядок слов' },
    { id: 'a2_119', type: 'order', q: 'Собери предложение', words: ['I','am','interested','in','music'], correct: 'I am interested in music', topic: 'Порядок слов' },
    { id: 'a2_120', type: 'order', q: 'Собери предложение', words: ['How','much','does','this','cost'], correct: 'How much does this cost', topic: 'Порядок слов' },

    // ─── РАСШИРЕНИЕ: ПОВСЕДНЕВНЫЕ СИТУАЦИИ ───
    { id: 'a2_121', type: 'choice', q: 'В кафе: «Мне чашку кофе, пожалуйста»', opts: ['I want coffee','A cup of coffee, please','Give me coffee','Coffee please'], correct: 1, topic: 'Ситуации' },
    { id: 'a2_122', type: 'choice', q: 'В магазине: «Сколько это стоит?»', opts: ['How are you?','How much is it?','What is it?','Where is it?'], correct: 1, topic: 'Ситуации' },
    { id: 'a2_123', type: 'choice', q: 'Спрашиваешь дорогу:', opts: ['Where is the bank?','What is the bank?','Who is the bank?','When is the bank?'], correct: 0, topic: 'Ситуации' },
    { id: 'a2_124', type: 'choice', q: 'В отеле: «Я хочу забронировать номер»', opts: ['I want a room','I would like to book a room','Give me a room','Room please'], correct: 1, topic: 'Ситуации' },
    { id: 'a2_125', type: 'choice', q: 'В ресторане: «Можно меню?»', opts: ['Menu','Can I have the menu?','Give me menu','I want menu'], correct: 1, topic: 'Ситуации' },
    { id: 'a2_126', type: 'choice', q: 'Опаздываешь: «Извини за опоздание»', opts: ['Sorry for being late','I am late','Sorry','Excuse me'], correct: 0, topic: 'Ситуации' },
    { id: 'a2_127', type: 'choice', q: 'Спрашиваешь время:', opts: ['What time is it?','How is time?','When time?','Where time?'], correct: 0, topic: 'Ситуации' },
    { id: 'a2_128', type: 'choice', q: 'В такси: «Остановите здесь, пожалуйста»', opts: ['Stop here, please','Stop, please','Here stop please','Please stop here now'], correct: 0, topic: 'Ситуации' },
    { id: 'a2_129', type: 'choice', q: 'Покупка билета: «Один билет в Лондон»', opts: ['One ticket to London','Ticket London','London one ticket','I want ticket'], correct: 0, topic: 'Ситуации' },
    { id: 'a2_130', type: 'choice', q: 'Знакомство: «Откуда ты?»', opts: ['Where are you from?','Who are you?','How are you?','What are you?'], correct: 0, topic: 'Ситуации' },

    // ─── РАСШИРЕНИЕ: ХОББИ / РАБОТА / ПОГОДА ───
    { id: 'a2_131', type: 'choice', q: 'Как "читать книги" по-английски?', opts: ['read books','see books','look books','watch books'], correct: 0, topic: 'Хобби' },
    { id: 'a2_132', type: 'choice', q: 'Как "смотреть фильмы"?', opts: ['see films','watch films','look films','read films'], correct: 1, topic: 'Хобби' },
    { id: 'a2_133', type: 'choice', q: 'Как "играть в футбол"?', opts: ['play football','do football','go football','make football'], correct: 0, topic: 'Хобби' },
    { id: 'a2_134', type: 'choice', q: 'Как "плавать"?', opts: ['go swimming','play swim','do swim','make swim'], correct: 0, topic: 'Хобби' },
    { id: 'a2_135', type: 'choice', q: 'Как "работать в офисе"?', opts: ['work in an office','work on office','work at office building','work office'], correct: 0, topic: 'Работа' },
    { id: 'a2_136', type: 'choice', q: 'Как "ходить на работу"?', opts: ['go to work','go work','go at work','go in work'], correct: 0, topic: 'Работа' },
    { id: 'a2_137', type: 'choice', q: 'Как "погода солнечная"?', opts: ['The weather is sunny','Weather sunny','Sunny weather is','Is sunny'], correct: 0, topic: 'Погода' },
    { id: 'a2_138', type: 'choice', q: 'Как "идёт дождь"?', opts: ['It is raining','Rain is going','Rain falls','It raining'], correct: 0, topic: 'Погода' },
    { id: 'a2_139', type: 'choice', q: 'Как "идёт снег"?', opts: ['It is snowing','Snow is going','Snow falls','It snow'], correct: 0, topic: 'Погода' },
    { id: 'a2_140', type: 'choice', q: 'Как "очень жарко"?', opts: ['It is very hot','Very hot','Hot very','Is very hot'], correct: 0, topic: 'Погода' },

    // ─── ДОПОЛНИТЕЛЬНО: ФРАЗЫ ВЕЖЛИВОСТИ ───
    { id: 'a2_141', type: 'choice', q: 'Как вежливо попросить?', opts: ['Give me...','Could you...?','I want...','I need...'], correct: 1, topic: 'Вежливость' },
    { id: 'a2_142', type: 'choice', q: 'Как вежливо отказаться?', opts: ['No!','I am afraid I can\'t','Nope','Never'], correct: 1, topic: 'Вежливость' },
    { id: 'a2_143', type: 'choice', q: 'Как вежливо согласиться?', opts: ['Yes yes','Of course!','Yep','Yeah'], correct: 1, topic: 'Вежливость' },
    { id: 'a2_144', type: 'choice', q: 'Как извиниться за беспокойство?', opts: ['Sorry to bother you','Excuse','Hello','Please'], correct: 0, topic: 'Вежливость' },
    { id: 'a2_145', type: 'choice', q: 'Как попросить повторить?', opts: ['What?','Could you repeat, please?','Again!','Say again'], correct: 1, topic: 'Вежливость' },
    { id: 'a2_146', type: 'choice', q: 'Как попросить говорить медленнее?', opts: ['Slow!','Could you speak slower, please?','Faster please','Slowly now'], correct: 1, topic: 'Вежливость' },
    { id: 'a2_147', type: 'choice', q: 'Как сказать «Я не понимаю»?', opts: ['I not understand','I don\'t understand','Not understand me','No understand'], correct: 1, topic: 'Вежливость' },
    { id: 'a2_148', type: 'choice', q: 'Как спросить «Что это значит?»', opts: ['What means it?','What does it mean?','What is mean?','How mean?'], correct: 1, topic: 'Вежливость' },
    { id: 'a2_149', type: 'choice', q: 'Как сказать «Хорошего дня!»?', opts: ['Good day!','Have a nice day!','Nice day you','Day good!'], correct: 1, topic: 'Вежливость' },
    { id: 'a2_150', type: 'choice', q: 'Как сказать «До скорого!»?', opts: ['To soon!','See you soon!','Goodbye soon','Bye!'], correct: 1, topic: 'Вежливость' },
  ];
