<script>
  window.LINGUA_DATA = window.LINGUA_DATA || {};
  window.LINGUA_DATA.C1 = [
    // ─── ADVANCED INVERSION ───
    { id: 'c1_1', type: 'choice', q: 'Hardly ___ the room when the phone rang.', opts: ['I had entered','had I entered','I entered','did I entered'], correct: 1, topic: 'Инверсия' },
    { id: 'c1_2', type: 'choice', q: 'Not only ___ late, but he also forgot the documents.', opts: ['he was','was he','he is','is he'], correct: 1, topic: 'Инверсия' },
    { id: 'c1_3', type: 'choice', q: 'Never ___ such a beautiful place.', opts: ['I have seen','have I seen','I saw','did I saw'], correct: 1, topic: 'Инверсия' },
    { id: 'c1_4', type: 'choice', q: 'Little ___ that he would win.', opts: ['he knew','did he know','he knows','he did know'], correct: 1, topic: 'Инверсия' },
    { id: 'c1_5', type: 'choice', q: 'No sooner ___ than it started raining.', opts: ['we left','had we left','we had left','did we leave'], correct: 1, topic: 'Инверсия' },
    { id: 'c1_6', type: 'choice', q: 'Only then ___ the truth.', opts: ['I realized','did I realize','I realize','I did realize'], correct: 1, topic: 'Инверсия' },
    { id: 'c1_7', type: 'choice', q: 'Rarely ___ such talent.', opts: ['we see','do we see','we do see','see we'], correct: 1, topic: 'Инверсия' },
    { id: 'c1_8', type: 'choice', q: 'Under no circumstances ___ leave the building.', opts: ['you should','should you','you must','must you'], correct: 1, topic: 'Инверсия' },
    { id: 'c1_9', type: 'choice', q: 'On no account ___ tell anyone.', opts: ['you must','must you','you should','should you'], correct: 1, topic: 'Инверсия' },
    { id: 'c1_10', type: 'choice', q: 'Nowhere ___ such poverty.', opts: ['I have seen','have I seen','I saw','did I saw'], correct: 1, topic: 'Инверсия' },

    // ─── MODAL PERFECTS ───
    { id: 'c1_11', type: 'choice', q: 'You ___ have told me earlier!', opts: ['should','must','can','would'], correct: 0, topic: 'Modal Perfects' },
    { id: 'c1_12', type: 'choice', q: 'He ___ have finished already — it\'s too early.', opts: ['must','can\'t','should','might'], correct: 1, topic: 'Modal Perfects' },
    { id: 'c1_13', type: 'choice', q: 'She ___ have taken the wrong bus.', opts: ['must','can','should','would'], correct: 0, topic: 'Modal Perfects' },
    { id: 'c1_14', type: 'choice', q: 'You ___ have been more careful.', opts: ['should','must','can','would'], correct: 0, topic: 'Modal Perfects' },
    { id: 'c1_15', type: 'choice', q: 'They ___ have arrived by now.', opts: ['should','must','can','would'], correct: 0, topic: 'Modal Perfects' },
    { id: 'c1_16', type: 'choice', q: 'I ___ have left my keys at home.', opts: ['must','should','can','would'], correct: 0, topic: 'Modal Perfects' },
    { id: 'c1_17', type: 'choice', q: 'He ___ have been a doctor — he knows nothing about medicine.', opts: ['must','can\'t','should','might'], correct: 1, topic: 'Modal Perfects' },
    { id: 'c1_18', type: 'choice', q: 'She ___ have forgotten our meeting.', opts: ['must','can','should','would'], correct: 0, topic: 'Modal Perfects' },

    // ─── ADVANCED CONDITIONALS ───
    { id: 'c1_19', type: 'choice', q: 'If I had studied medicine, I ___ a doctor now.', opts: ['will be','would be','am','was'], correct: 1, topic: 'Cond Adv' },
    { id: 'c1_20', type: 'choice', q: 'If she were more careful, she ___ that mistake yesterday.', opts: ['wouldn\'t make','wouldn\'t have made','didn\'t make','doesn\'t make'], correct: 1, topic: 'Cond Adv' },
    { id: 'c1_21', type: 'choice', q: 'If he ___ taller, he would have joined the team.', opts: ['were','was','had been','is'], correct: 1, topic: 'Cond Adv' },
    { id: 'c1_22', type: 'choice', q: '___ you need any help, please call me.', opts: ['Should','Would','Could','Might'], correct: 0, topic: 'Cond Adv' },
    { id: 'c1_23', type: 'choice', q: 'If it ___ for your help, I would have failed.', opts: ['wasn\'t','weren\'t','hadn\'t been','isn\'t'], correct: 2, topic: 'Cond Adv' },
    { id: 'c1_24', type: 'choice', q: 'Were I ___ you, I would apologize.', opts: ['—','in','as','like'], correct: 0, topic: 'Cond Adv' },
    { id: 'c1_25', type: 'choice', q: 'Had I known, I ___ differently.', opts: ['acted','would act','would have acted','will act'], correct: 2, topic: 'Cond Adv' },
    { id: 'c1_26', type: 'choice', q: 'But for your support, I ___ finished.', opts: ['wouldn\'t have','didn\'t','hadn\'t','haven\'t'], correct: 0, topic: 'Cond Adv' },
    { id: 'c1_27', type: 'choice', q: 'Provided that you ___ on time, we will go.', opts: ['arrive','will arrive','arrived','arriving'], correct: 0, topic: 'Cond Adv' },
    { id: 'c1_28', type: 'choice', q: 'Supposing you ___ the lottery, what would you do?', opts: ['win','won','will win','winning'], correct: 1, topic: 'Cond Adv' },

    // ─── CLEFT SENTENCES ───
    { id: 'c1_29', type: 'choice', q: '___ I need is a good rest.', opts: ['What','That','Which','It'], correct: 0, topic: 'Cleft' },
    { id: 'c1_30', type: 'choice', q: 'It was John ___ called you.', opts: ['who','which','what','whose'], correct: 0, topic: 'Cleft' },
    { id: 'c1_31', type: 'choice', q: 'It was yesterday ___ I met her.', opts: ['that','which','when','where'], correct: 0, topic: 'Cleft' },
    { id: 'c1_32', type: 'choice', q: '___ happened was that he lost his keys.', opts: ['What','That','Which','It'], correct: 0, topic: 'Cleft' },
    { id: 'c1_33', type: 'choice', q: 'It is money ___ he wants, not fame.', opts: ['that','which','what','who'], correct: 0, topic: 'Cleft' },
    { id: 'c1_34', type: 'choice', q: 'The reason ___ I called was to say sorry.', opts: ['why','that','which','what'], correct: 0, topic: 'Cleft' },
    { id: 'c1_35', type: 'choice', q: '___ I love about her is her kindness.', opts: ['What','That','Which','It'], correct: 0, topic: 'Cleft' },

    // ─── SUBJUNCTIVE ───
    { id: 'c1_36', type: 'choice', q: 'I suggest that he ___ on time.', opts: ['is','be','was','will be'], correct: 1, topic: 'Subjunctive' },
    { id: 'c1_37', type: 'choice', q: 'It\'s essential that she ___ present.', opts: ['is','be','was','will be'], correct: 1, topic: 'Subjunctive' },
    { id: 'c1_38', type: 'choice', q: 'The doctor insisted that he ___ rest.', opts: ['rests','rest','rested','will rest'], correct: 1, topic: 'Subjunctive' },
    { id: 'c1_39', type: 'choice', q: 'I demand that you ___ the truth.', opts: ['tell','tells','told','will tell'], correct: 0, topic: 'Subjunctive' },
    { id: 'c1_40', type: 'choice', q: 'If only he ___ here now!', opts: ['is','were','was','be'], correct: 1, topic: 'Subjunctive' },
    { id: 'c1_41', type: 'choice', q: 'God ___ the Queen!', opts: ['save','saves','saved','saving'], correct: 0, topic: 'Subjunctive' },
    { id: 'c1_42', type: 'choice', q: 'It\'s vital that everyone ___ informed.', opts: ['is','be','was','will be'], correct: 1, topic: 'Subjunctive' },

    // ─── ADVANCED PHRASAL VERBS ───
    { id: 'c1_43', type: 'choice', q: 'He ___ the proposal without a second thought.', opts: ['turned down','turned off','turned up','turned in'], correct: 0, topic: 'Phrasal Adv' },
    { id: 'c1_44', type: 'choice', q: 'I can\'t ___ his behaviour any longer.', opts: ['put up with','put on with','put in with','put off with'], correct: 0, topic: 'Phrasal Adv' },
    { id: 'c1_45', type: 'choice', q: 'The scandal ___ a lot of controversy.', opts: ['gave rise to','gave up to','gave in to','gave out to'], correct: 0, topic: 'Phrasal Adv' },
    { id: 'c1_46', type: 'choice', q: 'We need to ___ this issue before it escalates.', opts: ['nip in the bud','nip off','nip on','nip out'], correct: 0, topic: 'Phrasal Adv' },
    { id: 'c1_47', type: 'choice', q: 'He ___ at the last minute.', opts: ['backed out','backed in','backed up','backed off'], correct: 0, topic: 'Phrasal Adv' },
    { id: 'c1_48', type: 'choice', q: 'She ___ the entire plan.', opts: ['put forward','put in','put out','put on'], correct: 0, topic: 'Phrasal Adv' },
    { id: 'c1_49', type: 'choice', q: 'The meeting ___ into an argument.', opts: ['degenerated','turned into','went off','came out'], correct: 0, topic: 'Phrasal Adv' },
    { id: 'c1_50', type: 'choice', q: 'He ___ some very interesting points.', opts: ['brought up','brought in','brought off','brought out'], correct: 0, topic: 'Phrasal Adv' },
    { id: 'c1_51', type: 'choice', q: 'I came ___ an old photo yesterday.', opts: ['across','up','in','out'], correct: 0, topic: 'Phrasal Adv' },
    { id: 'c1_52', type: 'choice', q: 'She ___ her success to hard work.', opts: ['attributes','contributes','distributes','substitutes'], correct: 0, topic: 'Phrasal Adv' },

    // ─── ACADEMIC VOCABULARY ───
    { id: 'c1_53', type: 'choice', q: '«Тем не менее» — самый формальный вариант:', opts: ['Nevertheless','But','Still','However'], correct: 0, topic: 'Академ. лексика' },
    { id: 'c1_54', type: 'choice', q: '«В связи с вышесказанным»:', opts: ['In light of the above','In light of the top','In light of the over','In light of the up'], correct: 0, topic: 'Академ. лексика' },
    { id: 'c1_55', type: 'choice', q: '«Принимая во внимание»:', opts: ['Taking into account','Taking in account','Taking on account','Taking for account'], correct: 0, topic: 'Академ. лексика' },
    { id: 'c1_56', type: 'choice', q: '«Существенный» (академич.):', opts: ['Substantial','Big','Large','Huge'], correct: 0, topic: 'Академ. лексика' },
    { id: 'c1_57', type: 'choice', q: '«Демонстрировать»:', opts: ['Demonstrate','Show','Tell','Speak'], correct: 0, topic: 'Академ. лексика' },
    { id: 'c1_58', type: 'choice', q: '«Подчёркивать важность»:', opts: ['Emphasize','Show','Tell','Say'], correct: 0, topic: 'Академ. лексика' },
    { id: 'c1_59', type: 'choice', q: '«Провести исследование»:', opts: ['Conduct research','Make research','Do research','Have research'], correct: 0, topic: 'Академ. лексика' },
    { id: 'c1_60', type: 'choice', q: '«Сделать вывод»:', opts: ['Draw a conclusion','Make a conclusion','Do a conclusion','Have a conclusion'], correct: 0, topic: 'Академ. лексика' },

    // ─── IDIOMS ADVANCED ───
    { id: 'c1_61', type: 'choice', q: 'To bite the bullet =', opts: ['Стиснуть зубы и сделать','Укусить пулю','Быть храбрым','Стрелять'], correct: 0, topic: 'Идиомы Adv' },
    { id: 'c1_62', type: 'choice', q: 'To let sleeping dogs lie =', opts: ['Не будить лихо','Дать собаке спать','Молчать','Уйти'], correct: 0, topic: 'Идиомы Adv' },
    { id: 'c1_63', type: 'choice', q: 'To beat around the bush =', opts: ['Ходить вокруг да около','Бить куст','Гулять','Спорить'], correct: 0, topic: 'Идиомы Adv' },
    { id: 'c1_64', type: 'choice', q: 'To throw in the towel =', opts: ['Сдаться','Бросить полотенце','Уйти','Победить'], correct: 0, topic: 'Идиомы Adv' },
    { id: 'c1_65', type: 'choice', q: 'To sit on the fence =', opts: ['Занимать нейтральную позицию','Сесть на забор','Молчать','Уйти'], correct: 0, topic: 'Идиомы Adv' },
    { id: 'c1_66', type: 'choice', q: 'To go the extra mile =', opts: ['Приложить дополнительные усилия','Пройти милю','Уехать','Быть упорным'], correct: 0, topic: 'Идиомы Adv' },
    { id: 'c1_67', type: 'choice', q: 'To have a chip on your shoulder =', opts: ['Быть обиженным','Иметь чип','Быть сильным','Быть богатым'], correct: 0, topic: 'Идиомы Adv' },
    { id: 'c1_68', type: 'choice', q: 'To cut corners =', opts: ['Экономить (в плохом смысле)','Резать углы','Быстро делать','Идти коротким путём'], correct: 0, topic: 'Идиомы Adv' },
    { id: 'c1_69', type: 'choice', q: 'To be on the ball =', opts: ['Быть сообразительным','На мяче','Играть','Устать'], correct: 0, topic: 'Идиомы Adv' },
    { id: 'c1_70', type: 'choice', q: 'To call it a day =', opts: ['Закончить на сегодня','Позвонить','Уйти','Начать'], correct: 0, topic: 'Идиомы Adv' },

    // ─── NUANCED USAGE ───
    { id: 'c1_71', type: 'choice', q: 'It\'s high time we ___ this issue.', opts: ['address','addressed','will address','addressing'], correct: 1, topic: 'Тонкости' },
    { id: 'c1_72', type: 'choice', q: 'I\'d rather you ___ smoke here.', opts: ['don\'t','didn\'t','won\'t','haven\'t'], correct: 1, topic: 'Тонкости' },
    { id: 'c1_73', type: 'choice', q: 'The more you practice, ___ you become.', opts: ['the better','better','the best','best'], correct: 0, topic: 'Тонкости' },
    { id: 'c1_74', type: 'choice', q: '___ having studied hard, he failed.', opts: ['Despite','Although','However','Even'], correct: 0, topic: 'Тонкости' },
    { id: 'c1_75', type: 'choice', q: 'He is said ___ very rich.', opts: ['be','to be','being','is'], correct: 1, topic: 'Тонкости' },
    { id: 'c1_76', type: 'choice', q: 'I had my car ___ yesterday.', opts: ['repair','repaired','repairing','to repair'], correct: 1, topic: 'Тонкости' },
    { id: 'c1_77', type: 'choice', q: 'It\'s worth ___ this book.', opts: ['read','reading','to read','reads'], correct: 1, topic: 'Тонкости' },
    { id: 'c1_78', type: 'choice', q: 'There is no point ___ about it.', opts: ['worry','worrying','to worry','worried'], correct: 1, topic: 'Тонкости' },
    { id: 'c1_79', type: 'choice', q: 'I can\'t help ___ about it.', opts: ['think','thinking','to think','thought'], correct: 1, topic: 'Тонкости' },
    { id: 'c1_80', type: 'choice', q: 'He denied ___ the money.', opts: ['steal','stealing','to steal','stolen'], correct: 1, topic: 'Тонкости' },
    { id: 'c1_81', type: 'choice', q: 'I\'m used to ___ up early.', opts: ['get','getting','got','gets'], correct: 1, topic: 'Тонкости' },
    { id: 'c1_82', type: 'choice', q: 'She suggested ___ to the cinema.', opts: ['go','going','to go','gone'], correct: 1, topic: 'Тонкости' },

    // ─── TRANSLATE ───
    { id: 'c1_83', type: 'translate', q: 'Переведи: «Едва я вошёл, как зазвонил телефон»', answers: ['hardly had i entered when the phone rang'], topic: 'Перевод' },
    { id: 'c1_84', type: 'translate', q: 'Переведи: «Не только он опоздал, но и забыл документы»', answers: ['not only was he late but he also forgot the documents'], topic: 'Перевод' },
    { id: 'c1_85', type: 'translate', q: 'Переведи: «Ни при каких обстоятельствах ты не должен уходить»', answers: ['under no circumstances should you leave'], topic: 'Перевод' },
    { id: 'c1_86', type: 'translate', q: 'Переведи: «Если бы не твоя помощь, я бы провалился»', answers: ['if it hadnt been for your help i would have failed','if it were not for your help i would have failed'], topic: 'Перевод' },
    { id: 'c1_87', type: 'translate', q: 'Переведи: «Я настаиваю на том, чтобы он пришёл»', answers: ['i insist that he come','i insist on his coming'], topic: 'Перевод' },
    { id: 'c1_88', type: 'translate', q: 'Переведи: «Он, говорят, уехал за границу»', answers: ['he is said to have gone abroad'], topic: 'Перевод' },
    { id: 'c1_89', type: 'translate', q: 'Переведи: «Мне нужно, чтобы машину починили»', answers: ['i need to have my car repaired','i need to get my car repaired'], topic: 'Перевод' },
    { id: 'c1_90', type: 'translate', q: 'Переведи: «Нет смысла спорить с ним»', answers: ['there is no point in arguing with him','theres no point in arguing with him'], topic: 'Перевод' },
    { id: 'c1_91', type: 'translate', q: 'Переведи: «Он отрицал, что украл деньги»', answers: ['he denied stealing the money','he denied having stolen the money'], topic: 'Перевод' },
    { id: 'c1_92', type: 'translate', q: 'Переведи: «Чем больше ты практикуешься, тем лучше становишься»', answers: ['the more you practice the better you become'], topic: 'Перевод' },
    { id: 'c1_93', type: 'translate', q: 'Переведи: «Несмотря на то, что он усердно учился, он провалился»', answers: ['despite having studied hard he failed','although he studied hard he failed'], topic: 'Перевод' },
    { id: 'c1_94', type: 'translate', q: 'Переведи: «Я бы предпочёл, чтобы ты не курил здесь»', answers: ['id rather you didnt smoke here'], topic: 'Перевод' },
    { id: 'c1_95', type: 'translate', q: 'Переведи: «Пора бы нам заняться этим вопросом»', answers: ['its high time we addressed this issue'], topic: 'Перевод' },
    { id: 'c1_96', type: 'translate', q: 'Переведи: «Он заслуживает похвалы»', answers: ['he deserves to be praised','he deserves praise'], topic: 'Перевод' },
    { id: 'c1_97', type: 'translate', q: 'Переведи: «Что мне нужно, так это хороший отдых»', answers: ['what i need is a good rest'], topic: 'Перевод' },
    { id: 'c1_98', type: 'translate', q: 'Переведи: «Только тогда я понял правду»', answers: ['only then did i realize the truth'], topic: 'Перевод' },
    { id: 'c1_99', type: 'translate', q: 'Переведи: «Не успели мы выйти, как пошёл дождь»', answers: ['no sooner had we left than it started raining','hardly had we left when it started raining'], topic: 'Перевод' },
    { id: 'c1_100', type: 'translate', q: 'Переведи: «Я не могу больше это терпеть»', answers: ['i cant put up with it anymore','i cannot put up with this any longer'], topic: 'Перевод' },

    // ─── LISTEN ───
    { id: 'c1_101', type: 'listen', q: 'Прослушай и напиши', audio: 'Hardly had I entered when the phone rang.', answers: ['hardly had i entered when the phone rang'], topic: 'Аудирование' },
    { id: 'c1_102', type: 'listen', q: 'Прослушай и напиши', audio: 'Not only was he late, but he also lied.', answers: ['not only was he late but he also lied'], topic: 'Аудирование' },
    { id: 'c1_103', type: 'listen', q: 'Прослушай и напиши', audio: 'Under no circumstances should you leave.', answers: ['under no circumstances should you leave'], topic: 'Аудирование' },
    { id: 'c1_104', type: 'listen', q: 'Прослушай и напиши', audio: 'If it had not been for your help, I would have failed.', answers: ['if it had not been for your help i would have failed','if it hadnt been for your help i would have failed'], topic: 'Аудирование' },
    { id: 'c1_105', type: 'listen', q: 'Прослушай и напиши', audio: 'I insist that he come on time.', answers: ['i insist that he come on time'], topic: 'Аудирование' },
    { id: 'c1_106', type: 'listen', q: 'Прослушай и напиши', audio: 'He is said to have gone abroad.', answers: ['he is said to have gone abroad'], topic: 'Аудирование' },
    { id: 'c1_107', type: 'listen', q: 'Прослушай и напиши', audio: 'What I need is a good rest.', answers: ['what i need is a good rest'], topic: 'Аудирование' },
    { id: 'c1_108', type: 'listen', q: 'Прослушай и напиши', audio: 'Only then did I realize the truth.', answers: ['only then did i realize the truth'], topic: 'Аудирование' },
    { id: 'c1_109', type: 'listen', q: 'Прослушай и напиши', audio: 'No sooner had we left than it started raining.', answers: ['no sooner had we left than it started raining'], topic: 'Аудирование' },
    { id: 'c1_110', type: 'listen', q: 'Прослушай и напиши', audio: 'The more you practice, the better you become.', answers: ['the more you practice the better you become'], topic: 'Аудирование' },

    // ─── SPEAK ───
    { id: 'c1_111', type: 'speak', q: 'Произнеси вслух', target: 'Hardly had I entered when the phone rang.', topic: 'Произношение' },
    { id: 'c1_112', type: 'speak', q: 'Произнеси вслух', target: 'Not only was he late, but he also lied.', topic: 'Произношение' },
    { id: 'c1_113', type: 'speak', q: 'Произнеси вслух', target: 'Under no circumstances should you leave.', topic: 'Произношение' },
    { id: 'c1_114', type: 'speak', q: 'Произнеси вслух', target: 'If it had not been for your help, I would have failed.', topic: 'Произношение' },
    { id: 'c1_115', type: 'speak', q: 'Произнеси вслух', target: 'I insist that he come on time.', topic: 'Произношение' },
    { id: 'c1_116', type: 'speak', q: 'Произнеси вслух', target: 'He is said to have gone abroad.', topic: 'Произношение' },
    { id: 'c1_117', type: 'speak', q: 'Произнеси вслух', target: 'What I need is a good rest.', topic: 'Произношение' },
    { id: 'c1_118', type: 'speak', q: 'Произнеси вслух', target: 'Only then did I realize the truth.', topic: 'Произношение' },
    { id: 'c1_119', type: 'speak', q: 'Произнеси вслух', target: 'No sooner had we left than it started raining.', topic: 'Произношение' },
    { id: 'c1_120', type: 'speak', q: 'Произнеси вслух', target: 'The more you practice, the better you become.', topic: 'Произношение' },

    // ─── WORD ORDER ───
    { id: 'c1_121', type: 'order', q: 'Собери предложение', words: ['Hardly','had','I','entered','when','the','phone','rang'], correct: 'Hardly had I entered when the phone rang', topic: 'Порядок слов' },
    { id: 'c1_122', type: 'order', q: 'Собери предложение', words: ['Not','only','was','he','late','but','he','lied'], correct: 'Not only was he late but he lied', topic: 'Порядок слов' },
    { id: 'c1_123', type: 'order', q: 'Собери предложение', words: ['Under','no','circumstances','should','you','leave'], correct: 'Under no circumstances should you leave', topic: 'Порядок слов' },
    { id: 'c1_124', type: 'order', q: 'Собери предложение', words: ['What','I','need','is','a','good','rest'], correct: 'What I need is a good rest', topic: 'Порядок слов' },
    { id: 'c1_125', type: 'order', q: 'Собери предложение', words: ['Only','then','did','I','realize','the','truth'], correct: 'Only then did I realize the truth', topic: 'Порядок слов' },
    { id: 'c1_126', type: 'order', q: 'Собери предложение', words: ['He','is','said','to','have','gone','abroad'], correct: 'He is said to have gone abroad', topic: 'Порядок слов' },
    { id: 'c1_127', type: 'order', q: 'Собери предложение', words: ['I','insist','that','he','come','on','time'], correct: 'I insist that he come on time', topic: 'Порядок слов' },
    { id: 'c1_128', type: 'order', q: 'Собери предложение', words: ['The','more','you','practice','the','better','you','become'], correct: 'The more you practice the better you become', topic: 'Порядок слов' },
    { id: 'c1_129', type: 'order', q: 'Собери предложение', words: ['No','sooner','had','we','left','than','it','rained'], correct: 'No sooner had we left than it rained', topic: 'Порядок слов' },
    { id: 'c1_130', type: 'order', q: 'Собери предложение', words: ['It','was','John','who','called','you'], correct: 'It was John who called you', topic: 'Порядок слов' },

    // ─── РАСШИРЕНИЕ: ТОНКИЕ СТИЛИСТИЧЕСКИЕ ───
    { id: 'c1_131', type: 'choice', q: '«Нельзя не признать, что...»', opts: ['It cannot be denied that','It cannot deny that','It is not denied that','Not denied that'], correct: 0, topic: 'Стиль' },
    { id: 'c1_132', type: 'choice', q: '«Стоит отметить, что...»', opts: ['It is worth noting that','It worths noting that','It is worth to note that','Worth noting that'], correct: 0, topic: 'Стиль' },
    { id: 'c1_133', type: 'choice', q: '«Вне всякого сомнения»', opts: ['Beyond any doubt','Beyond all doubting','Over any doubt','Out of doubt'], correct: 0, topic: 'Стиль' },
    { id: 'c1_134', type: 'choice', q: '«Строго говоря»', opts: ['Strictly speaking','Strict speaking','Strictly speak','Speaking strictly'], correct: 0, topic: 'Стиль' },
    { id: 'c1_135', type: 'choice', q: '«В конечном счёте»', opts: ['Ultimately','At the end','In end','To the end'], correct: 0, topic: 'Стиль' },
    { id: 'c1_136', type: 'choice', q: '«Следует подчеркнуть»', opts: ['It should be emphasized','It should emphasize','It should emphasizes','Should emphasize'], correct: 0, topic: 'Стиль' },
    { id: 'c1_137', type: 'choice', q: '«Исходя из вышесказанного»', opts: ['Based on the above','Basing on above','Based above','On base above'], correct: 0, topic: 'Стиль' },
    { id: 'c1_138', type: 'choice', q: '«Не подлежит сомнению»', opts: ['It is beyond question','It is over question','It is out of question','It is no question'], correct: 0, topic: 'Стиль' },
    { id: 'c1_139', type: 'choice', q: '«Как правило»', opts: ['As a rule','By a rule','On a rule','In a rule'], correct: 0, topic: 'Стиль' },
    { id: 'c1_140', type: 'choice', q: '«В подавляющем большинстве случаев»', opts: ['In the vast majority of cases','In vast majority cases','In the majority of vast cases','By vast majority'], correct: 0, topic: 'Стиль' },

    // ─── РАСШИРЕНИЕ: СЛОЖНЫЕ СТРУКТУРЫ ───
    { id: 'c1_141', type: 'choice', q: '___ having been warned, he continued.', opts: ['Despite','Although','However','Even'], correct: 0, topic: 'Структуры' },
    { id: 'c1_142', type: 'choice', q: 'The problem ___ is that we lack resources.', opts: ['being solved','to solve','solving','solved'], correct: 1, topic: 'Структуры' },
    { id: 'c1_143', type: 'choice', q: 'He is believed ___ the money.', opts: ['steal','to have stolen','stealing','stolen'], correct: 1, topic: 'Структуры' },
    { id: 'c1_144', type: 'choice', q: 'I would sooner ___ at home tonight.', opts: ['stay','to stay','staying','stayed'], correct: 0, topic: 'Структуры' },
    { id: 'c1_145', type: 'choice', q: 'Hardly ___ when the storm broke.', opts: ['we had arrived','had we arrived','we arrived','did we arrive'], correct: 1, topic: 'Структуры' },
    { id: 'c1_146', type: 'choice', q: 'She would rather ___ than stay home.', opts: ['go out','to go out','going out','went out'], correct: 0, topic: 'Структуры' },
    { id: 'c1_147', type: 'choice', q: 'The proposal ___ by the committee.', opts: ['turned down','was turned down','is turning down','turns down'], correct: 1, topic: 'Структуры' },
    { id: 'c1_148', type: 'choice', q: 'Not until later ___ the truth.', opts: ['I learned','did I learn','I learn','I did learn'], correct: 1, topic: 'Структуры' },
    { id: 'c1_149', type: 'choice', q: '___ no account should you tell him.', opts: ['On','In','At','By'], correct: 0, topic: 'Структуры' },
    { id: 'c1_150', type: 'choice', q: 'Rarely ___ such a remarkable performance.', opts: ['I have seen','have I seen','I saw','did I saw'], correct: 1, topic: 'Структуры' },
  ];
    </script>
