<script>
  window.LINGUA_DATA = window.LINGUA_DATA || {};
  window.LINGUA_DATA.C2 = [
    // ─── ADVANCED INVERSION ───
    { id: 'c2_1', type: 'choice', q: 'Not until much later ___ the truth.', opts: ['I learned','did I learn','I learn','I did learn'], correct: 1, topic: 'Инверсия C2' },
    { id: 'c2_2', type: 'choice', q: 'Nowhere ___ such craftsmanship.', opts: ['you will find','will you find','you find','find you'], correct: 1, topic: 'Инверсия C2' },
    { id: 'c2_3', type: 'choice', q: 'Only after the meeting ___ the mistake.', opts: ['we realized','did we realize','we realize','realize we'], correct: 1, topic: 'Инверсия C2' },
    { id: 'c2_4', type: 'choice', q: 'In no way ___ responsible for the accident.', opts: ['he is','is he','he was','was he'], correct: 1, topic: 'Инверсия C2' },
    { id: 'c2_5', type: 'choice', q: 'So absorbed ___ in his work that he forgot to eat.', opts: ['he was','was he','he is','is he'], correct: 1, topic: 'Инверсия C2' },
    { id: 'c2_6', type: 'choice', q: 'Such ___ his anger that he could not speak.', opts: ['was','is','were','be'], correct: 0, topic: 'Инверсия C2' },
    { id: 'c2_7', type: 'choice', q: 'Many a time ___ his advice.', opts: ['I sought','sought I','I seek','seek I'], correct: 0, topic: 'Инверсия C2' },
    { id: 'c2_8', type: 'choice', q: 'At no time ___ the truth.', opts: ['he revealed','did he reveal','he reveals','reveals he'], correct: 1, topic: 'Инверсия C2' },
    { id: 'c2_9', type: 'choice', q: 'Scarcely ___ when the storm broke.', opts: ['we had arrived','had we arrived','we arrived','did we arrive'], correct: 1, topic: 'Инверсия C2' },
    { id: 'c2_10', type: 'choice', q: 'Not for a moment ___ the story.', opts: ['I believed','did I believe','I believe','believe I'], correct: 1, topic: 'Инверсия C2' },

    // ─── LITERARY / FORMAL CONSTRUCTIONS ───
    { id: 'c2_11', type: 'choice', q: '___ the circumstances, we had to cancel.', opts: ['Given','Giving','Gave','Gives'], correct: 0, topic: 'Формальное' },
    { id: 'c2_12', type: 'choice', q: 'He is ___ to be the best candidate.', opts: ['said','saying','says','say'], correct: 0, topic: 'Формальное' },
    { id: 'c2_13', type: 'choice', q: 'Little ___ that he would win.', opts: ['he knew','did he know','he knows','he did know'], correct: 1, topic: 'Формальное' },
    { id: 'c2_14', type: 'choice', q: 'Rarely ___ such dedication.', opts: ['we see','do we see','we do see','see we'], correct: 1, topic: 'Формальное' },
    { id: 'c2_15', type: 'choice', q: 'That ___ said, we must proceed.', opts: ['being','been','is','was'], correct: 0, topic: 'Формальное' },
    { id: 'c2_16', type: 'choice', q: 'Be that as it ___, we must try.', opts: ['may','might','will','can'], correct: 0, topic: 'Формальное' },
    { id: 'c2_17', type: 'choice', q: '___ it not for his help, we would fail.', opts: ['Were','Was','Is','Be'], correct: 0, topic: 'Формальное' },
    { id: 'c2_18', type: 'choice', q: '___ the event of an emergency, call 999.', opts: ['In','On','At','By'], correct: 0, topic: 'Формальное' },
    { id: 'c2_19', type: 'choice', q: '___ the understanding that you will come.', opts: ['On','In','At','By'], correct: 0, topic: 'Формальное' },
    { id: 'c2_20', type: 'choice', q: 'This is ___ to cause concern.', opts: ['bound','bounded','binding','bounden'], correct: 0, topic: 'Формальное' },

    // ─── SUBJUNCTIVE ADVANCED ───
    { id: 'c2_21', type: 'choice', q: 'I insist that he ___ present.', opts: ['is','be','was','will be'], correct: 1, topic: 'Subjunctive C2' },
    { id: 'c2_22', type: 'choice', q: 'It\'s essential that everyone ___ informed.', opts: ['is','be','was','will be'], correct: 1, topic: 'Subjunctive C2' },
    { id: 'c2_23', type: 'choice', q: 'The court ordered that he ___ released.', opts: ['is','be','was','will be'], correct: 1, topic: 'Subjunctive C2' },
    { id: 'c2_24', type: 'choice', q: 'If only he ___ here now!', opts: ['is','were','was','be'], correct: 1, topic: 'Subjunctive C2' },
    { id: 'c2_25', type: 'choice', q: 'God ___ the King!', opts: ['save','saves','saved','saving'], correct: 0, topic: 'Subjunctive C2' },
    { id: 'c2_26', type: 'choice', q: 'It is imperative that she ___ on time.', opts: ['is','be','was','will be'], correct: 1, topic: 'Subjunctive C2' },
    { id: 'c2_27', type: 'choice', q: 'He suggested that the meeting ___ postponed.', opts: ['is','be','was','will be'], correct: 1, topic: 'Subjunctive C2' },
    { id: 'c2_28', type: 'choice', q: '___ he be found guilty, he would appeal.', opts: ['Should','Would','Could','Might'], correct: 0, topic: 'Subjunctive C2' },

    // ─── IDIOMS & SLANG ───
    { id: 'c2_29', type: 'choice', q: 'To be "over the moon" =', opts: ['Быть очень счастливым','Быть на луне','Мечтать','Грустить'], correct: 0, topic: 'Сленг' },
    { id: 'c2_30', type: 'choice', q: 'To "spill the beans" =', opts: ['Выдать секрет','Пролить бобы','Готовить','Есть'], correct: 0, topic: 'Сленг' },
    { id: 'c2_31', type: 'choice', q: 'To "hit the sack" =', opts: ['Лечь спать','Ударить мешок','Устать','Упасть'], correct: 0, topic: 'Сленг' },
    { id: 'c2_32', type: 'choice', q: 'To "pull someone\'s leg" =', opts: ['Шутить, разыгрывать','Тянуть ногу','Бегать','Танцевать'], correct: 0, topic: 'Сленг' },
    { id: 'c2_33', type: 'choice', q: 'To "throw someone under the bus" =', opts: ['Подставить кого-то','Бросить под автобус','Толкнуть','Уронить'], correct: 0, topic: 'Сленг' },
    { id: 'c2_34', type: 'choice', q: 'To be "on cloud nine" =', opts: ['Быть на седьмом небе','Быть в облаках','Мечтать','Быть уставшим'], correct: 0, topic: 'Сленг' },
    { id: 'c2_35', type: 'choice', q: 'To "bite off more than you can chew" =', opts: ['Взять на себя слишком много','Жевать много','Есть быстро','Проглотить'], correct: 0, topic: 'Сленг' },
    { id: 'c2_36', type: 'choice', q: 'To "burn the midnight oil" =', opts: ['Работать допоздна','Жечь масло','Спать','Готовить'], correct: 0, topic: 'Сленг' },
    { id: 'c2_37', type: 'choice', q: 'To "cost a fortune" =', opts: ['Стоить целое состояние','Стоить удачу','Быть дешёвым','Быть дорогим подарком'], correct: 0, topic: 'Сленг' },
    { id: 'c2_38', type: 'choice', q: 'To "go cold turkey" =', opts: ['Резко бросить привычку','Есть холодную индейку','Замерзнуть','Голодать'], correct: 0, topic: 'Сленг' },
    { id: 'c2_39', type: 'choice', q: 'To "have a blast" =', opts: ['Отлично провести время','Взорваться','Устать','Заболеть'], correct: 0, topic: 'Сленг' },
    { id: 'c2_40', type: 'choice', q: 'To "call the shots" =', opts: ['Руководить','Звонить','Стрелять','Кричать'], correct: 0, topic: 'Сленг' },
    { id: 'c2_41', type: 'choice', q: 'To be "under the weather" =', opts: ['Плохо себя чувствовать','Под дождём','Замерзнуть','Устать'], correct: 0, topic: 'Сленг' },
    { id: 'c2_42', type: 'choice', q: 'To "break the ice" =', opts: ['Растопить лёд (начать общение)','Разбить лёд','Заморозить','Упасть'], correct: 0, topic: 'Сленг' },
    { id: 'c2_43', type: 'choice', q: 'To "let the cat out of the bag" =', opts: ['Выдать секрет','Выпустить кота','Потерять','Убежать'], correct: 0, topic: 'Сленг' },
    { id: 'c2_44', type: 'choice', q: 'To "kill two birds with one stone" =', opts: ['Сделать два дела сразу','Убить птиц','Потерять время','Потратить деньги'], correct: 0, topic: 'Сленг' },
    { id: 'c2_45', type: 'choice', q: 'To "let someone off the hook" =', opts: ['Простить, отпустить','Снять с крючка','Помочь','Поймать'], correct: 0, topic: 'Сленг' },
    { id: 'c2_46', type: 'choice', q: 'To "be in hot water" =', opts: ['Быть в беде','Быть в кипятке','Замерзнуть','Устать'], correct: 0, topic: 'Сленг' },
    { id: 'c2_47', type: 'choice', q: 'To "have butterflies in your stomach" =', opts: ['Нервничать','Есть бабочек','Быть голодным','Заболеть'], correct: 0, topic: 'Сленг' },
    { id: 'c2_48', type: 'choice', q: 'To "cut to the chase" =', opts: ['Перейти к сути','Резать','Гнаться','Прыгать'], correct: 0, topic: 'Сленг' },

    // ─── REGISTER / STYLE ───
    { id: 'c2_49', type: 'choice', q: 'Формальный вариант «I want to know»:', opts: ['I should like to know','I wanna know','I wanna know','I want knowing'], correct: 0, topic: 'Регистр' },
    { id: 'c2_50', type: 'choice', q: 'Неформальный вариант «How do you do?»:', opts: ['How\'s it going?','How do you do?','How are you?','What\'s up?'], correct: 0, topic: 'Регистр' },
    { id: 'c2_51', type: 'choice', q: 'Формальный вариант «to get»:', opts: ['to obtain','to grab','to snag','to score'], correct: 0, topic: 'Регистр' },
    { id: 'c2_52', type: 'choice', q: 'Формальный вариант «to find out»:', opts: ['to ascertain','to figure out','to catch','to see'], correct: 0, topic: 'Регистр' },
    { id: 'c2_53', type: 'choice', q: 'Формальный вариант «to think about»:', opts: ['to consider','to ponder on','to think of','to wonder'], correct: 0, topic: 'Регистр' },
    { id: 'c2_54', type: 'choice', q: 'Неформальный вариант «It is my opinion that»:', opts: ['I reckon','I opine','I consider that','I hold that'], correct: 0, topic: 'Регистр' },
    { id: 'c2_55', type: 'choice', q: 'Формальный вариант «a lot of»:', opts: ['a considerable amount of','loads of','tons of','heaps of'], correct: 0, topic: 'Регистр' },
    { id: 'c2_56', type: 'choice', q: 'Формальный вариант «so» (как вводное):', opts: ['Therefore','So','Thus anyway','Like'], correct: 0, topic: 'Регистр' },

    // ─── NUANCED MEANINGS ───
    { id: 'c2_57', type: 'choice', q: 'Разница: "childish" vs "childlike"?', opts: ['childish — плохо, childlike — хорошо','Оба одинаковы','childlike — плохо','Нет разницы'], correct: 0, topic: 'Нюансы' },
    { id: 'c2_58', type: 'choice', q: '"Historic" vs "historical"?', opts: ['historic — важный, historical — связанный с историей','Оба одинаковы','historic — связанный с историей','Нет разницы'], correct: 0, topic: 'Нюансы' },
    { id: 'c2_59', type: 'choice', q: '"Economic" vs "economical"?', opts: ['economic — экономика, economical — экономный','Оба одинаковы','economical — экономика','Нет разницы'], correct: 0, topic: 'Нюансы' },
    { id: 'c2_60', type: 'choice', q: '"Sensible" vs "sensitive"?', opts: ['sensible — разумный, sensitive — чувствительный','Оба одинаковы','sensible — чувствительный','Нет разницы'], correct: 0, topic: 'Нюансы' },
    { id: 'c2_61', type: 'choice', q: '"Continual" vs "continuous"?', opts: ['continual — повторяющийся, continuous — непрерывный','Оба одинаковы','continual — непрерывный','Нет разницы'], correct: 0, topic: 'Нюансы' },
    { id: 'c2_62', type: 'choice', q: '"Imply" vs "infer"?', opts: ['imply — намекать, infer — догадываться','Оба одинаковы','imply — догадываться','Нет разницы'], correct: 0, topic: 'Нюансы' },
    { id: 'c2_63', type: 'choice', q: '"Farther" vs "further"?', opts: ['farther — расстояние, further — дополнительно','Оба одинаковы','farther — дополнительно','Нет разницы'], correct: 0, topic: 'Нюансы' },
    { id: 'c2_64', type: 'choice', q: '"Fewer" vs "less"?', opts: ['fewer — с исчисляемыми, less — с неисчисляемыми','Оба одинаковы','fewer — с неисчисляемыми','Нет разницы'], correct: 0, topic: 'Нюансы' },
    { id: 'c2_65', type: 'choice', q: '"Amount" vs "number"?', opts: ['amount — с неисчисляемыми, number — с исчисляемыми','Оба одинаковы','amount — с исчисляемыми','Нет разницы'], correct: 0, topic: 'Нюансы' },
    { id: 'c2_66', type: 'choice', q: '"Lay" vs "lie"?', opts: ['lay — класть (переходный), lie — лежать','Оба одинаковы','lay — лежать','Нет разницы'], correct: 0, topic: 'Нюансы' },

    // ─── TRANSLATE ───
    { id: 'c2_67', type: 'translate', q: 'Переведи: «Не успел я опомниться, как всё изменилось»', answers: ['before i knew it everything had changed','before i knew it everything changed'], topic: 'Перевод' },
    { id: 'c2_68', type: 'translate', q: 'Переведи: «Никогда прежде я не встречал такого человека»', answers: ['never before had i met such a person'], topic: 'Перевод' },
    { id: 'c2_69', type: 'translate', q: 'Переведи: «Строго говоря, это не совсем верно»', answers: ['strictly speaking that is not quite correct','strictly speaking its not quite true'], topic: 'Перевод' },
    { id: 'c2_70', type: 'translate', q: 'Переведи: «Нельзя не признать его вклад»', answers: ['one cannot deny his contribution','it cannot be denied that he contributed'], topic: 'Перевод' },
    { id: 'c2_71', type: 'translate', q: 'Переведи: «Он был на седьмом небе от счастья»', answers: ['he was over the moon','he was on cloud nine'], topic: 'Перевод' },
    { id: 'c2_72', type: 'translate', q: 'Переведи: «Он выдал секрет»', answers: ['he let the cat out of the bag','he spilled the beans'], topic: 'Перевод' },
    { id: 'c2_73', type: 'translate', q: 'Переведи: «Я не выношу, когда со мной так обращаются»', answers: ['i cannot stand being treated like that','i cant stand being treated like that'], topic: 'Перевод' },
    { id: 'c2_74', type: 'translate', q: 'Переведи: «Что бы ни случилось, я останусь»', answers: ['whatever happens i will stay','whatever may happen i will stay'], topic: 'Перевод' },
    { id: 'c2_75', type: 'translate', q: 'Переведи: «Было бы ошибкой думать, что...»', answers: ['it would be a mistake to think that'], topic: 'Перевод' },
    { id: 'c2_76', type: 'translate', q: 'Переведи: «Стоит отметить его исключительный талант»', answers: ['it is worth noting his exceptional talent'], topic: 'Перевод' },
    { id: 'c2_77', type: 'translate', q: 'Переведи: «Мало кто знает правду»', answers: ['few people know the truth','few know the truth'], topic: 'Перевод' },
    { id: 'c2_78', type: 'translate', q: 'Переведи: «Не то чтобы я возражал, но...»', answers: ['not that i object but','its not that i object but'], topic: 'Перевод' },
    { id: 'c2_79', type: 'translate', q: 'Переведи: «Вне всякого сомнения, он лучший»', answers: ['beyond any doubt he is the best'], topic: 'Перевод' },
    { id: 'c2_80', type: 'translate', q: 'Переведи: «Он пролил свет на эту проблему»', answers: ['he shed light on this problem','he shed light on the issue'], topic: 'Перевод' },
    { id: 'c2_81', type: 'translate', q: 'Переведи: «Не подлежит сомнению его честность»', answers: ['his honesty is beyond question'], topic: 'Перевод' },
    { id: 'c2_82', type: 'translate', q: 'Переведи: «В конечном счёте, всё решится само»', answers: ['ultimately everything will work out','ultimately it will all work out'], topic: 'Перевод' },
    { id: 'c2_83', type: 'translate', q: 'Переведи: «Исходя из вышесказанного, можно сделать вывод»', answers: ['based on the above we can conclude','from the above we can conclude'], topic: 'Перевод' },
    { id: 'c2_84', type: 'translate', q: 'Переведи: «Он подставил своего коллегу»', answers: ['he threw his colleague under the bus'], topic: 'Перевод' },
    { id: 'c2_85', type: 'translate', q: 'Переведи: «Редко встретишь такого человека»', answers: ['rarely do you meet such a person','rarely do we meet such a person'], topic: 'Перевод' },
    { id: 'c2_86', type: 'translate', q: 'Переведи: «Да будет так»', answers: ['so be it'], topic: 'Перевод' },
    { id: 'c2_87', type: 'translate', q: 'Переведи: «Ему палец в рот не клади»', answers: ['hes not one to be trifled with','he is not someone to be trifled with'], topic: 'Перевод' },
    { id: 'c2_88', type: 'translate', q: 'Переведи: «Он знает своё дело»', answers: ['he knows his stuff','he knows his business'], topic: 'Перевод' },
    { id: 'c2_89', type: 'translate', q: 'Переведи: «Короче говоря, всё прошло хорошо»', answers: ['in short everything went well'], topic: 'Перевод' },
    { id: 'c2_90', type: 'translate', q: 'Переведи: «Не мешало бы тебе извиниться»', answers: ['you might want to apologize','you should apologize'], topic: 'Перевод' },
    { id: 'c2_91', type: 'translate', q: 'Переведи: «Он держит всё под контролем»', answers: ['he has everything under control','he keeps everything under control'], topic: 'Перевод' },
    { id: 'c2_92', type: 'translate', q: 'Переведи: «Всё в порядке вещей»', answers: ['its all par for the course','it is all par for the course'], topic: 'Перевод' },
    { id: 'c2_93', type: 'translate', q: 'Переведи: «Он произвёл хорошее впечатление»', answers: ['he made a good impression'], topic: 'Перевод' },
    { id: 'c2_94', type: 'translate', q: 'Переведи: «Не будем спешить с выводами»', answers: ['lets not jump to conclusions','we should not jump to conclusions'], topic: 'Перевод' },
    { id: 'c2_95', type: 'translate', q: 'Переведи: «Он пошёл на риск»', answers: ['he took a risk','he took the plunge'], topic: 'Перевод' },
    { id: 'c2_96', type: 'translate', q: 'Переведи: «Он выше этого»', answers: ['hes above that','he is above that'], topic: 'Перевод' },
    { id: 'c2_97', type: 'translate', q: 'Переведи: «Ему всё сошло с рук»', answers: ['he got away with it'], topic: 'Перевод' },
    { id: 'c2_98', type: 'translate', q: 'Переведи: «Я сыт по горло»', answers: ['i am fed up','im fed up','i have had enough'], topic: 'Перевод' },
    { id: 'c2_99', type: 'translate', q: 'Переведи: «Это просто верх наглости»', answers: ['thats the height of rudeness','this is the height of impudence'], topic: 'Перевод' },
    { id: 'c2_100', type: 'translate', q: 'Переведи: «В этом вся суть»', answers: ['thats the crux of the matter','that is the crux of the matter'], topic: 'Перевод' },

    // ─── LISTEN ───
    { id: 'c2_101', type: 'listen', q: 'Прослушай и напиши', audio: 'Not until much later did I learn the truth.', answers: ['not until much later did i learn the truth'], topic: 'Аудирование' },
    { id: 'c2_102', type: 'listen', q: 'Прослушай и напиши', audio: 'Never before had I met such a person.', answers: ['never before had i met such a person'], topic: 'Аудирование' },
    { id: 'c2_103', type: 'listen', q: 'Прослушай и напиши', audio: 'In no way is he responsible for the accident.', answers: ['in no way is he responsible for the accident'], topic: 'Аудирование' },
    { id: 'c2_104', type: 'listen', q: 'Прослушай и напиши', audio: 'Be that as it may, we must try.', answers: ['be that as it may we must try'], topic: 'Аудирование' },
    { id: 'c2_105', type: 'listen', q: 'Прослушай и напиши', audio: 'Strictly speaking, that is not quite correct.', answers: ['strictly speaking that is not quite correct','strictly speaking thats not quite correct'], topic: 'Аудирование' },
    { id: 'c2_106', type: 'listen', q: 'Прослушай и напиши', audio: 'It cannot be denied that he contributed.', answers: ['it cannot be denied that he contributed','it cant be denied that he contributed'], topic: 'Аудирование' },
    { id: 'c2_107', type: 'listen', q: 'Прослушай и напиши', audio: 'Rarely do you meet such a person.', answers: ['rarely do you meet such a person'], topic: 'Аудирование' },
    { id: 'c2_108', type: 'listen', q: 'Прослушай и напиши', audio: 'Should he be found guilty, he would appeal.', answers: ['should he be found guilty he would appeal'], topic: 'Аудирование' },
    { id: 'c2_109', type: 'listen', q: 'Прослушай и напиши', audio: 'Given the circumstances, we had to cancel.', answers: ['given the circumstances we had to cancel'], topic: 'Аудирование' },
    { id: 'c2_110', type: 'listen', q: 'Прослушай и напиши', audio: 'So absorbed was he in his work that he forgot to eat.', answers: ['so absorbed was he in his work that he forgot to eat'], topic: 'Аудирование' },

    // ─── SPEAK ───
    { id: 'c2_111', type: 'speak', q: 'Произнеси вслух', target: 'Not until much later did I learn the truth.', topic: 'Произношение' },
    { id: 'c2_112', type: 'speak', q: 'Произнеси вслух', target: 'Never before had I met such a person.', topic: 'Произношение' },
    { id: 'c2_113', type: 'speak', q: 'Произнеси вслух', target: 'In no way is he responsible for the accident.', topic: 'Произношение' },
    { id: 'c2_114', type: 'speak', q: 'Произнеси вслух', target: 'Be that as it may, we must try.', topic: 'Произношение' },
    { id: 'c2_115', type: 'speak', q: 'Произнеси вслух', target: 'Strictly speaking, that is not quite correct.', topic: 'Произношение' },
    { id: 'c2_116', type: 'speak', q: 'Произнеси вслух', target: 'It cannot be denied that he contributed.', topic: 'Произношение' },
    { id: 'c2_117', type: 'speak', q: 'Произнеси вслух', target: 'Rarely do you meet such a person.', topic: 'Произношение' },
    { id: 'c2_118', type: 'speak', q: 'Произнеси вслух', target: 'Should he be found guilty, he would appeal.', topic: 'Произношение' },
    { id: 'c2_119', type: 'speak', q: 'Произнеси вслух', target: 'Given the circumstances, we had to cancel.', topic: 'Произношение' },
    { id: 'c2_120', type: 'speak', q: 'Произнеси вслух', target: 'So absorbed was he in his work that he forgot to eat.', topic: 'Произношение' },

    // ─── WORD ORDER ───
    { id: 'c2_121', type: 'order', q: 'Собери предложение', words: ['Not','until','much','later','did','I','learn','the','truth'], correct: 'Not until much later did I learn the truth', topic: 'Порядок слов' },
    { id: 'c2_122', type: 'order', q: 'Собери предложение', words: ['Never','before','had','I','met','such','a','person'], correct: 'Never before had I met such a person', topic: 'Порядок слов' },
    { id: 'c2_123', type: 'order', q: 'Собери предложение', words: ['In','no','way','is','he','responsible'], correct: 'In no way is he responsible', topic: 'Порядок слов' },
    { id: 'c2_124', type: 'order', q: 'Собери предложение', words: ['Be','that','as','it','may','we','must','try'], correct: 'Be that as it may we must try', topic: 'Порядок слов' },
    { id: 'c2_125', type: 'order', q: 'Собери предложение', words: ['Strictly','speaking','that','is','not','quite','correct'], correct: 'Strictly speaking that is not quite correct', topic: 'Порядок слов' },
    { id: 'c2_126', type: 'order', q: 'Собери предложение', words: ['It','cannot','be','denied','that','he','contributed'], correct: 'It cannot be denied that he contributed', topic: 'Порядок слов' },
    { id: 'c2_127', type: 'order', q: 'Собери предложение', words: ['Rarely','do','you','meet','such','a','person'], correct: 'Rarely do you meet such a person', topic: 'Порядок слов' },
    { id: 'c2_128', type: 'order', q: 'Собери предложение', words: ['Given','the','circumstances','we','had','to','cancel'], correct: 'Given the circumstances we had to cancel', topic: 'Порядок слов' },
    { id: 'c2_129', type: 'order', q: 'Собери предложение', words: ['At','no','time','did','he','reveal','the','truth'], correct: 'At no time did he reveal the truth', topic: 'Порядок слов' },
    { id: 'c2_130', type: 'order', q: 'Собери предложение', words: ['Many','a','time','I','sought','his','advice'], correct: 'Many a time I sought his advice', topic: 'Порядок слов' },

    // ─── РАСШИРЕНИЕ: ЛИТЕРАТУРНЫЕ ОБОРОТЫ ───
    { id: 'c2_131', type: 'choice', q: '«Едва ли можно сомневаться»', opts: ['It is hardly to be doubted','It hardly is doubted','Hardly to doubt','Not doubt'], correct: 0, topic: 'Литературные' },
    { id: 'c2_132', type: 'choice', q: '«Отнюдь не»', opts: ['Far from','Far away','Far to','Far out'], correct: 0, topic: 'Литературные' },
    { id: 'c2_133', type: 'choice', q: '«Отнюдь не так просто»', opts: ['Far from easy','Far of easy','Far to easy','Far so easy'], correct: 0, topic: 'Литературные' },
    { id: 'c2_134', type: 'choice', q: '«Всё же, тем не менее»', opts: ['All the same','All same','All of same','Same all'], correct: 0, topic: 'Литературные' },
    { id: 'c2_135', type: 'choice', q: '«Что касается меня»', opts: ['As for me','As me','For me as','Me as'], correct: 0, topic: 'Литературные' },
    { id: 'c2_136', type: 'choice', q: '«В свою очередь»', opts: ['In turn','On turn','At turn','By turn'], correct: 0, topic: 'Литературные' },
    { id: 'c2_137', type: 'choice', q: '«Со своей стороны»', opts: ['For my part','On my part','At my part','By my part'], correct: 0, topic: 'Литературные' },
    { id: 'c2_138', type: 'choice', q: '«Следует заметить вскользь»', opts: ['It should be noted in passing','It should note passing','Noted passing it','In passing noted'], correct: 0, topic: 'Литературные' },
    { id: 'c2_139', type: 'choice', q: '«Оставляя в стороне»', opts: ['Leaving aside','Leaving apart','Left aside','Leave aside'], correct: 0, topic: 'Литературные' },
    { id: 'c2_140', type: 'choice', q: '«Не говоря уже о»', opts: ['Let alone','Let go','Let in','Let on'], correct: 0, topic: 'Литературные' },

    // ─── РАСШИРЕНИЕ: СЛОЖНЕЙШИЕ КОНСТРУКЦИИ ───
    { id: 'c2_141', type: 'choice', q: 'He was ___ to have left the country.', opts: ['thought','thinking','thinks','think'], correct: 0, topic: 'Сложнейшие' },
    { id: 'c2_142', type: 'choice', q: 'The suspect is believed ___ the country.', opts: ['to have left','leaving','leave','left'], correct: 0, topic: 'Сложнейшие' },
    { id: 'c2_143', type: 'choice', q: 'I had my doubts ___ the deal.', opts: ['about','on','in','at'], correct: 0, topic: 'Сложнейшие' },
    { id: 'c2_144', type: 'choice', q: 'She is rumoured ___ married.', opts: ['to be','being','be','was'], correct: 0, topic: 'Сложнейшие' },
    { id: 'c2_145', type: 'choice', q: 'Seldom ___ such dedication.', opts: ['have I seen','I have seen','I saw','saw I'], correct: 0, topic: 'Сложнейшие' },
    { id: 'c2_146', type: 'choice', q: 'No sooner said than ___.', opts: ['done','do','did','does'], correct: 0, topic: 'Сложнейшие' },
    { id: 'c2_147', type: 'choice', q: 'Come what ___, I will stand by you.', opts: ['may','might','will','can'], correct: 0, topic: 'Сложнейшие' },
    { id: 'c2_148', type: 'choice', q: 'He would sooner die ___ surrender.', opts: ['than','then','as','that'], correct: 0, topic: 'Сложнейшие' },
    { id: 'c2_149', type: 'choice', q: 'Little did she know what ___ ahead.', opts: ['lay','lied','laid','lies'], correct: 0, topic: 'Сложнейшие' },
    { id: 'c2_150', type: 'choice', q: 'Had it not been for her, we ___ lost.', opts: ['would have been','would be','had been','were'], correct: 0, topic: 'Сложнейшие' },
  ];
      </script>
